### ISSUE TITLE
Is number of followers a really good metric?

### ISSUE THREAD

**Issue by CaioHVectorA** [kauefraga/themis#13]
Based on thread: [Bsky thread](https://bsky.app/profile/zoedsoupe.zeetech.io/post/3l4a5etoqym2p)

And some absurd values:

![image](https://github.com/user-attachments/assets/255de51d-ae55-4152-ba07-9f8bca291777)

i dont stopped yet to analysis the code deeply, is it based on a calc with followers_count / following_count ?

**Comment by CaioHVectorA** [comment]
## Testing with some big accounts:
![image](https://github.com/user-attachments/assets/0e38305f-ca96-4609-9898-d59323a849bc)
### 5M Followers | 2 Following

![image](https://github.com/user-attachments/assets/d74c4764-f6df-4aa0-b069-3a8dc3e2ea51)
### 300k Followers | 500 Following

**Comment by CaioHVectorA** [comment]
Maybe a normalization or a limit will be a good one.

**Comment by rdenadai** [comment]
I open a PR to avoid this explosion, and a tentative to normalize the final result as a percentage.
The value calculated by the initials rules has a greater weight and the followers/following dynamic has a small weight (it can duplicate the original value).
That does affect the final score, but has small amount of weight in overall ...
