### ISSUE TITLE
Analysis page layout issue

### ISSUE THREAD

**Issue by kauefraga** [kauefraga/themis#14]
![image](https://github.com/user-attachments/assets/fce20b46-7cc1-48a9-a89f-c7a12022330b)
![image](https://github.com/user-attachments/assets/cf50e503-871f-407f-bc71-d40f836753db)

**Comment by CaioHVectorA** [comment]
The issue continues after @jotavetech PR ?

**Comment by kauefraga** [comment]
No, I just forgot to close it lol
