### ISSUE TITLE
Autocomplete in input

### ISSUE THREAD

**Issue by CaioHVectorA** [kauefraga/themis#4]
In the atproto API is there some way to implement that? I think it gets a huge UX improvement
![image](https://github.com/user-attachments/assets/bbe63f2c-3483-4bbe-8b63-a981df1b710f)

**Comment by kauefraga** [comment]
Awesome suggestion, I think it will improve the UX a lot too! However, I don't know if it's possible to implement using the atproto API.

I saw that you forked the project, did you find something about it?

**Comment by kauefraga** [comment]
Looking in the devtools network tab I found that the Bluesky is using the lexicon [`app.bsky.actor.searchActorsTypeahead`](https://docs.bsky.app/docs/api/app-bsky-actor-search-actors-typeahead) to make the autocompletion.

![image](https://github.com/user-attachments/assets/30b00063-0683-4e6d-8074-92650a556648)

**Comment by CaioHVectorA** [comment]
No, i just dropped the idea here.

> Awesome suggestion, I think it will improve the UX a lot too! However, I don't know if it's possible to implement using the atproto API.
> 
> I saw that you forked the project, did you find something about it?

**Comment by CaioHVectorA** [comment]
> Looking in the devtools network tab I found that the Bluesky is using the lexicon [`app.bsky.actor.searchActorsTypeahead`](https://docs.bsky.app/docs/api/app-bsky-actor-search-actors-typeahead) to make the autocompletion.
> 
> ![image](https://private-user-images.githubusercontent.com/88486000/367539145-30b00063-0683-4e6d-8074-92650a556648.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYzNDI5MjcsIm5iZiI6MTcyNjM0MjYyNywicGF0aCI6Ii84ODQ4NjAwMC8zNjc1MzkxNDUtMzBiMDAwNjMtMDY4My00ZTZkLTgwNzQtOTI2NTBhNTU2NjQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE0VDE5MzcwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MWY2ZTUyOWI0MzczYjQzM2NjOWRmNjNkMGY0MDZmOTUzN2RlNTQxNjc3ZmMzODk4ZGVkM2I0Mzg1NjQ2MjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FXfyHqUmXpPIcy4pLbDwP6NgjuNxXyDksGsXFktxdIY)

Good find!
