### ISSUE TITLE
Add some navigation in score page

### ISSUE THREAD

**Issue by CaioHVectorA** [kauefraga/themis#9]
When the user is redirected to their score page, his dont have any clickable to navigate or make anything.
![image](https://github.com/user-attachments/assets/7845c555-0d73-4254-a248-46f0d9d7d6a2)

I thought about two alternatives:
- A back arrow in top to redirect to root
- A input to redirect to other score page

They can be used simultaneously

**Comment by kauefraga** [comment]
Another great suggestion, thanks!

**Comment by kauefraga** [comment]
The PR #10 closes this issue.
